/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainApp.java
 *
 * Created on 29/08/2012, 05:56:11 PM
 */
package iu;

import iu.panels.*;
import iu.dialogs.*;
import java.awt.CardLayout;

/**
 *
 * @author user
 */
public class MainApp extends javax.swing.JFrame {
    private PanelWelcome welcome = new PanelWelcome();
    private PanelGame panelJuego = new PanelGame(this);
    private DialAbout acercaDe = new DialAbout(this);
    private DialCredits creditos = new DialCredits(this);
    private DialDifficulty confDificultad = new DialDifficulty(this);
    private DialGraphics confGraficos = new DialGraphics(this);

    /** Creates new form MainApp */
    public MainApp() {
        initComponents();
        iniciarComponentes();
    }

    public void iniciarComponentes() {
        this.setLocation(150, 100);
        panelInicio.setLayout(new CardLayout());
        panelInicio.add(welcome, "welcome");
        panelInicio.add(panelJuego, "game");

    }
    
    public void verPanelWelcome(){
        ((CardLayout)panelInicio.getLayout()).show(panelInicio, "welcome");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuItemGraficos = new javax.swing.JMenuItem();
        mnuItemDificultad = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuItemAcercaDe = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuItemCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jMenu1.setText("Juego");

        jMenuItem5.setText("Nueva Partida");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Configuración");

        mnuItemGraficos.setText("Gráficos");
        mnuItemGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGraficosActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemGraficos);

        mnuItemDificultad.setText("Dificultad");
        mnuItemDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDificultadActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemDificultad);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Ayuda");

        mnuItemAcercaDe.setText("Acerca del juego");
        mnuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemAcercaDe);
        jMenu3.add(jSeparator1);

        mnuItemCreditos.setText("Créditos");
        mnuItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCreditosActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemCreditos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ((CardLayout)panelInicio.getLayout()).show(panelInicio, "game");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCreditosActionPerformed
        creditos.setVisible(true);
    }//GEN-LAST:event_mnuItemCreditosActionPerformed

    private void mnuItemDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDificultadActionPerformed
        confDificultad.setVisible(true);
    }//GEN-LAST:event_mnuItemDificultadActionPerformed

    private void mnuItemGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGraficosActionPerformed
        confGraficos.setVisible(true);
    }//GEN-LAST:event_mnuItemGraficosActionPerformed

    private void mnuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAcercaDeActionPerformed
        acercaDe.setVisible(true);
    }//GEN-LAST:event_mnuItemAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuItemAcercaDe;
    private javax.swing.JMenuItem mnuItemCreditos;
    private javax.swing.JMenuItem mnuItemDificultad;
    private javax.swing.JMenuItem mnuItemGraficos;
    private javax.swing.JPanel panelInicio;
    // End of variables declaration//GEN-END:variables
}
